<template>
  <Article :article="article">
    <h1>ProLeap transformation pipeline</h1>
    <p>The ProLeap platform implements a code transformation pipeline, which in its frontend extracts program structure from COBOL and Visual Basic 6.0 source code and in its backend transforms this program structure to Java source code, reports and code metrics.</p>
    <hr class="section-divider">
    <p><span class="dropCap">T</span>he ProLeap frontend is constituted by parsers for COBOL and Visual Basic 6.0, which we have implemented based on the <a href="http://www.antlr.org">ANTLR 4</a> parser generator framework. In the year 2015, we published the parsers under an open source license.</p>
    <p>As a result, the <a href="https://github.com/uwol/proleap-cobol-parser">ProLeap COBOL parser</a> has been applied by legacy modernization companies for parsing COBOL source code, and a derivative of the <a href="https://github.com/uwol/proleap-vb6-parser">ProLeap VB 6.0 parser</a> is applied at core of the <a href="http://rubberduckvba.com">Rubberduck VBA project</a>, which enables unit testing, refactoring and code inspection in the Visual Basic Editor (VBE). This open source momentum strengthens the development of our parsers, and thus supports the quality of the program structure generated by the ProLeap frontend.</p>
    <p>The ProLeap backend is constituted by a rule-based transformation engine, which associates COBOL and Visual Basic 6.0 language patterns with Java code fragments. When applied on a program structure generated by the ProLeap frontend, Java source code is generated including accompanying resources such as <a href="https://maven.apache.org">MAVEN</a> project files.</p>
    <p>Selective parts of the generated source code depend on runtime libraries, which are provided as open source MAVEN dependencies. Thus the generated artifact does not depend on proprietary software and is not affected by a vendor lock-in. As the transformation engine is rule-based, the transformation process and thus the generated Java source code can be customized arbitrarily.</p>
    <h2>COBOL pipeline</h2>
    <p>
      <img
        src="/img/pages/blog/2018-01-02/cobol-pipeline.png"
        alt="COBOL transformation pipeline"
      >
    </p>
    <h2>Visual Basic 6.0 pipeline</h2>
    <p>
      <img
        src="/img/pages/blog/2018-01-02/vb6-pipeline.png"
        alt="VB 6.0 transformation pipeline"
      >
    </p>
  </Article>
</template>

<script>
import Article from '@/components/vue/blog/article/Article'
import { ARTICLES } from '@/config/blog'

export default {
  components: {
    Article
  },
  data () {
    return {
      article: ARTICLES['blog-2018-01-02']
    }
  }
}
</script>
