 IDENTIFICATION DIVISION.
 PROGRAM-ID. TOOMANYPARAGRAPHS.
 PROCEDURE DIVISION.
 SOME-SECTION-1 SECTION.
 SOME-PARAGRAPH.
 SOME_PARAGRAPH.
 SOME_PARAGRAPH.
 SOME_PARAGRAPH.
 SOME_PARAGRAPH.
 SOME-PARAGRAPH.
 SOME_PARAGRAPH.
 SOME_PARAGRAPH.
 SOME_PARAGRAPH.
 SOME_PARAGRAPH.
 SOME-SECTION-2 SECTION.
 SOME-PARAGRAPH.
 SOME_PARAGRAPH.
 SOME_PARAGRAPH.
 SOME_PARAGRAPH.
 SOME_PARAGRAPH.
 SOME-PARAGRAPH.
 SOME_PARAGRAPH.
 SOME_PARAGRAPH.
 SOME_PARAGRAPH.
 SOME_PARAGRAPH.
 SOME-SECTION-3 SECTION.
 SOME-PARAGRAPH.
 SOME_PARAGRAPH.
 SOME_PARAGRAPH.
 SOME_PARAGRAPH.
 SOME_PARAGRAPH.
 SOME-PARAGRAPH.
 SOME_PARAGRAPH.
 SOME_PARAGRAPH.
 SOME_PARAGRAPH.
 SOME_PARAGRAPH.
 SOME-SECTION-4 SECTION.
 SOME-PARAGRAPH.
 SOME_PARAGRAPH.
 SOME_PARAGRAPH.
 SOME_PARAGRAPH.
 SOME_PARAGRAPH.
 SOME-PARAGRAPH.
 SOME_PARAGRAPH.
 SOME_PARAGRAPH.
 SOME_PARAGRAPH.
 SOME_PARAGRAPH.
 SOME-SECTION-5 SECTION.
 SOME-PARAGRAPH.
 SOME_PARAGRAPH.
 SOME_PARAGRAPH.
 SOME_PARAGRAPH.
 SOME_PARAGRAPH.
 SOME-PARAGRAPH.
 SOME_PARAGRAPH.
 SOME_PARAGRAPH.
 SOME_PARAGRAPH.
 SOME_PARAGRAPH.
 SOME-SECTION-6 SECTION.
 SOME-PARAGRAPH.
 SOME_PARAGRAPH.
 SOME_PARAGRAPH.
 SOME_PARAGRAPH.
 SOME_PARAGRAPH.
 SOME-PARAGRAPH.
 SOME_PARAGRAPH.
 SOME_PARAGRAPH.
 SOME_PARAGRAPH.
 SOME_PARAGRAPH.